### ISSUE TITLE
Jobs panel remove button

### ISSUE THREAD

**Issue by dangunter** [kbase/narrative#105]
Have the remove button actually stop and remove the job from NJS (if running)

**Comment by briehl** [comment]
Since this overlaps with parts of #108, I'll address those parts in this issue as well (and comment on the other one when finished).

Here's the flow I think might work best, based on what I think will be the 3 main cases:
  1. Job is complete, user deletes job
    - should delete job, leave app/method cell unchanged. I thought it was a design "feature" that completed cells remain locked, so they stay linked to the data they generate, right?
  2. Job is in an error state, user deletes it
    - again, deletes job, but should unlock the cell. This should be the same behavior as the upcoming 'Cancel' button that'll appear in a running cell.
  3. Job is running, but user wants to cancel it.
    - same as above

All of these may also be available from the app/method cell. A running/error cell should have a cancel button that triggers the same behavior as clicking the 'x' in the job panel.

**Comment by briehl** [comment]
The cancel button is now there, and semi-works. It now triggers an event that should pop up a prompt to kill the job (if a job is linked to that cell). I also added an error state for app cells that colors it red.

Still to-do is the logic that deletes the job. This will need to route through njs_wrapper on the back end, since there are njs, ujs, and an agnostic "method" job type. That'll happen tomorrow.

**Comment by briehl** [comment]
Those cases all now work from the front end, there just needs to be a little backend logic to tell whatever service to cancel cell.

**Comment by briehl** [comment]
The backend's there now (Thanks Roman!). I also rewired how cells and jobs and such behave and talk to each other. Closing this issue.
