### ISSUE TITLE
Drag and drop is broken

### ISSUE THREAD

**Issue by dangunter** [kbase/narrative#129]
Drag and drop is broken due to a change in where the "kb-oid" attribute is added. This attribute is used to look the object up in the list when the DOM element is dropped. The element passed to DnD got changed, so the kb-oid attribute cannot be found, and dropping results in badness.

Two things need to be fixed:
(a) the function addDragAndDrop() should include the identifier as a parameter, so it can control where it is added, and add it to the right place
(b) The drop phase of DnD should check for failures in more places

**Comment by msneddon** [comment]
Sorry, must have been me who broke it... I switched the element being
dragged so that the advanced details aren't shown when dragged and metadata
text can be selected for copy and paste. It "looked" like DnD was still
basically working as before, but I guess I didn't look closely enough. I'll
try to help test and fix tomorrow.

**Comment by msneddon** [comment]
Ok, (a) at least should be fixed in ef06eee .

Also noticed a couple issues related to rendering the data viewers.  First,
the first time any viewer is launched, the data isn't rendered because the
method store has not returned the necessary information yet.  This should
be fixed by 2b5196d by adding a callback that waits for the method store to
return.  Second, the data viewers don't save state when the narrative is
saved.  I'm going to create a separate issue to track that.

**Comment by dangunter** [comment]
OK, good. Looks like it works to me, I am closing this issue.
